services:
  careassist-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careassist-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Backend port
      - PORT=5000

      # Connection to your external MariaDB
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
      - NODE_ENV=production
    networks:
      - careassist-net

  careassist-frontend:
    build:
      context: .
      dockerfile: frontend-web/Dockerfile
    container_name: careassist-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - careassist-net


networks:
  careassist-net:
    driver: bridge

